[[redirects]]
  from = "/search"
  to = "https://api.mysearch.com"
  status = 200
  force = true                    # COMMENT: ensure that we always redirect

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
