openapi: "3.0.0"
info:
  title: Список грядок
  version: 01.001.00

paths:
  /beds:
    get:
      tags: [Грядки]
      summary: Получить список грядок
      operationId: getBeds

      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: ./schemas/getBedsRs.yaml
